Fs=10000;
t=0:1/Fs:0.25;
Amplitudo=5;
c=sin(Amplitudo*pi*264*t);         %C
c_kres=sin(Amplitudo*pi*280.5*t);  %C#
d=sin(Amplitudo*pi*297*t);         %D
d_kres=sin(Amplitudo*pi*313.5*t);  %D#
e=sin(Amplitudo*pi*330*t);         %E
f=sin(Amplitudo*pi*352*t);         %F
f_kres=sin(Amplitudo*pi*374*t);    %F#
g=sin(Amplitudo*pi*396*t);         %G
g_kres=sin(Amplitudo*pi*418*t);    %G#
a=sin(Amplitudo*pi*440*t);         %A
a_kres=sin(Amplitudo*pi*467.5*t);  %A#
b=sin(Amplitudo*pi*495*t);         %B
ci=sin(Amplitudo*pi*528*t); ;      %C tinggi
ci_kres=sin(Amplitudo*pi*561*t);   %C# tinggi
di=sin(Amplitudo*pi*594*t);        %D tinggi
di_kres=sin(Amplitudo*pi*627*t);   %D# tinggi
ei=sin(Amplitudo*pi*660*t);        %E tinggi
fi=sin(Amplitudo*pi*704*t);        %F tinggi
fi_kres=sin(Amplitudo*pi*748*t);   %F# tinggi
gi=sin(Amplitudo*pi*792*t);        %G tinggi
gi_kres=sin(Amplitudo*pi*836*t);   %G# tinggi
ai=sin(Amplitudo*pi*880*t);        %A tinggi
ai_kres=sin(Amplitudo*pi*935*t);   %A# tinggi
bi=sin(Amplitudo*pi*990*t);        %B tinggi
nol=[zeros(size(t))];      %tunda

bag1=[bag2,bag3,bag4,nol,nol,nol,nol,bag2,bag3,bag4,nol,nol,nol,bag5,nol,nol,nol,bag6,nol,nol,nol,bag7,nol,nol,bag8,nol,nol,bag9,nol,nol,bag10]
bag2=[ci,b,ci,nol,e,e,nol,e,nol,d,nol,e,g,nol,e,nol,nol];
bag3=[e,f,g,a,a,ci,nol,nol,g,f,nol,e,nol,nol,nol];
bag4=[c,nol,d,nol,ci,nol,ci,nol,nol,ci,nol,b,b,nol,a,a,nol,g,nol,f,g,a,g,nol,nol]
bag5=[d,e,f,f,f,f,f,f,f,nol,nol,nol,nol,nol,e,f,g,g,g,g,g,g,g,nol,nol,nol,nol,nol,a,b,ci,ci,ci,ci,ci,ci,ci,nol,nol,nol,nol,nol,di,ei,di,di,di,di,di,di,nol,nol,nol,nol]
bag6=[b,nol,ci,nol,nol,ci,nol,nol,ci,nol,b,nol,nol]
bag7=[b,ci,nol,nol,b,a,nol,nol,g,g,nol,nol]
bag8=[e,f,nol,ci,nol,ci,nol,ci,nol,ci,nol,b,nol,a,nol,nol,nol,g,nol,e,nol,nol]
bag9=[a,b,ci,nol,nol,ci,nol,nol,nol,ci,nol,nol,b,nol,nol]
bag10=[e,f,nol,ci,nol,ci,nol,ci,nol,ci,nol,b,nol,a,a,a,b,b,b,ci,ci,ci]
sound(bag1,Fs)
